frase = str(input('Digite uma frase: ')).strip().upper()
letra = str(input('Digite a letra que deseja encontrar: ')).strip().upper()
print('A letra {} aparece {} vezes na frase'.format(letra, frase.count(letra)))
print('A primeira letra {} apareceu na {}° posição'.format(letra, frase.find(letra)+1))
print('A última letra {} apareceu na {}° posição'.format(letra, frase.rfind(letra)+1))
